image: Visual Studio 2022

init:
  - git config --global core.autocrlf input

environment:
  MSBUILD_LOGGER: C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll
  SN_EXE: C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7 Tools\x64\sn.exe
  SNK_FILE: Moq.snk
  FSHARPTYPES_DLL: .\tests\Moq.Tests\bin\Release\net472\Moq.Tests.FSharpTypes.dll

build_script:
  - dotnet restore Moq.sln # --logger:"%MSBUILD_LOGGER%"
  - dotnet build Moq.sln --configuration Release --no-restore # --logger:"%MSBUILD_LOGGER%"

before_test:
  - call "%SN_EXE%" -R %FSHARPTYPES_DLL% %SNK_FILE%

test_script:
  - dotnet test --no-build --configuration Release .\tests\Moq.Tests\Moq.Tests.csproj # --logger:"%MSBUILD_LOGGER%"

after_test:
  - dotnet pack Moq.sln --no-build --no-restore --configuration Release --output out # --logger:"%MSBUILD_LOGGER%"

deploy:
  - provider: NuGet
    api_key:
      secure: rPsxT+QJ8XP1tw0XuAtV6TXP9j1rhQXFEDXg66U1BAv80jdHKrgR8BQpiqZ8zLA7
    on:
      appveyor_repo_tag: true

nuget:
  project_feed: true

artifacts:
  - path: 'out\*.nupkg'
